#!/usr/bin/env zsh
# NOTICE: This script is meant to be sourced and NOT executed!


#====================================================================
# To start with a fresh set of aliases:
# alias alias=:



#====================================================================
# Easier navigation: .., ..., ...., ....., ~ and -
##
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"




#====================================================================
# Convenience
##
alias d="cd ~/Documents/Dropbox"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias p="cd ~/projects"
alias g="git"
alias h="history"
alias j="jobs"
alias grep=egrep
alias zshconfig="vim -p ~/.{zshenv,zshrc,zlogin,zlogout} ~/.zsh/{zpath,zexport,zalias,zsecure}"





#====================================================================
# get rid of fu'd "corrections"
alias cheat='nocorrect cheat'
alias gem='nocorrect gem'
alias zsh='nocorrect zsh'


# Less-,i
#alias less=$PAGER
#alias zless=$PAGER

alias h=history
alias j=jobs

#-----------------------------------------
# Directory and file system management
autoload -U zmv
alias mmv='noglob zmv -W'
alias zcp='noglob zmv -C'
alias zln='noglob zmv -L'
alias zsy='noglob zmv -Ls'


#====================================================================
# ls Operations
#
# Setup for gls(1), tree(1) and ls(1)
#
# Thanks to Mathias for the ls flavor check
#
#
####
# LSCOLORS for GNU ls and tree(1)
[[ -r ~/.dircolors ]] && eval $(gdircolors --sh ~/.dircolors)

# LS_COLORS for BSD ls
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

alias gls='command gls --color=auto -F'
alias ls='command ls -GF'
alias tree='command tree -lhF --filelimit 50 --dirsfirst'



#====================================================================
# Rsync-supported Operations
# TODO: NEEDS Review for proper options!
####
alias rmerge='rsync -aHE --acls --xattrs --fileflags --safe-links --update'




#====================================================================
# ZSH- File-Globbing and Advanced File Mgmnt
#
# Pre-Reqs:
#     zmodload -U zmv
#     setopt  EXTENDED_GLOB
####
#alias -g GB='





#====================================================================
# Pipelines and re-direction
####
alias -g CA="2>&1 | cat -A"
alias -g C='| wc -l'
alias -g DN=/dev/null
alias -g EG='|& egrep'
alias -g EH='|& head'
alias -g EL='|& less'
alias -g ELS='|& less -S'
alias -g ETL='|& tail -20'
alias -g ET='|& tail'
alias -g F=' | fmt -'
alias -g G='| egrep'
alias -g H='| head'
alias -g HL='|& head -20'
alias -g Sk="*~(*.bz2|*.gz|*.tgz|*.zip|*.z)"
alias -g LL="2>&1 | less"
alias -g L="| less"
alias -g LS='| less -S'
alias -g MM='| most'
alias -g M='| more'
alias -g NE="2> /dev/null"
alias -g NS='| sort -n'
alias -g NUL="> /dev/null 2>&1"
alias -g PIPE='|'
alias -g R=' > /c/aaa/tee.txt '
alias -g RNS='| sort -nr'
alias -g S='| sort'
alias -g TL='| tail -20'
alias -g T='| tail'
alias -g US='| sort -u'
alias -g VM=/var/log/messages
alias -g X0G='| xargs -0 egrep'
alias -g X0='| xargs -0'
alias -g XG='| xargs egrep'
alias -g X='| xargs'


# Set up some qnd references
hash -d instadmg=~/Repos/InstaDMG
hash -d cheats=~/Dropbox/Cheats



#====================================================================
# SOFTWARE TWEAKS
#
# Github cli
# Note: Temporarily resolves a conflict with a github
# ruby gem (/usr/bin/gh) installed as a system gem.
##

alias gh='/usr/local/share/npm/bin/gh'


# For bundled executables
alias -g BE='bundle exec'
alias veewee="BE veewee"
alias vwv="BE veewee vbox"
alias vwf="BE veewee fusion"

# For The Luggage
alias pmake='PKGBUILD_ON=1 make -e '


#====================================================================
#====================================================================
# From Mathias's dotfiles
#
#
#====================================================================
#====================================================================
# Gzip-enabled `curl`
alias gurl='curl --compressed'

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

#====================================================================
# Network Management
#
# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""



#====================================================================
# Software Utils
#
# update:     Get OS X Software Updates, and update installed Ruby gems,
#             Homebrew, npm, and their installed packages
# lscleanup:  Clean up LaunchServices to remove duplicates in the
#             “Open With” menu of the Info dialog window
# emptytrash: Empty the Trash on all mounted volumes and the main HDD
#             Also, clear Apple’s System Logs to improve shell startup speed
# hd:         Canonical hex dump; some systems have this symlinked
# md5sum:     OS X has no `md5sum`, so use `md5` as a fallback
# sha1sum:    OS X has no `sha1sum`, so use `shasum` as a fallback
# jsc:        JavaScriptCore REPL
# c:          Trim new lines and copy to clipboard
# cleanup:    Recursively delete `.DS_Store` files
# rot13:      ROT13-encode text. Works for decoding, too! ;)
# show/hide:  Show/Hide  hidden files in Finder
# showdesktop/hidedesktop: Hide/show all desktop icons (useful when presenting)
# urlencode:  URL-encode strings
# mergepdf:   Merge PDF files
#             Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
# spoton:     Enable Spotlight
# spotoff:    Disable Spotlight
# plistbuddy: Easier to type, but doesn't flush the updated cache
# badge:      Ring the terminal bell, and put a badge on
#             Terminal.app’s Dock icon (useful when executing
#             time-consuming commands)
# map:        Intuitive map function
#             For example, to list all directories that contain a
#             certain file: find . -name .gitignore | map dirname
# chromekill: Kill all the tabs in Chrome to free up memory
#             [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
#
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem update'
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

command -v hd > /dev/null || alias hd="hexdump -C"
command -v md5sum > /dev/null || alias md5sum="md5"
command -v sha1sum > /dev/null || alias sha1sum="shasum"

jscbin="/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc"
[ -e "${jscbin}" ] && alias jsc="${jscbin}"
unset jscbin

alias c="tr -d '\n' | pbcopy"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
alias rot13='tr a-zA-Z n-za-mN-ZA-M'
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
alias spotoff="sudo mdutil -a -i off"
alias spoton="sudo mdutil -a -i on"
alias plistbuddy="/usr/libexec/PlistBuddy"
alias badge="tput bl"
alias map="xargs -n1"

# # One of @janmoesen’s ProTip™s
# for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
# 	alias "$method"="lwp-request -m '$method'"
# done
#
# # Make Grunt print stack traces by default
# command -v grunt > /dev/null && alias grunt="grunt --stack"
#
# # Stuff I never really use but cannot delete either because of http://xkcd.com/530/
# alias stfu="osascript -e 'set volume output muted true'"
# alias pumpitup="osascript -e 'set volume 7'"
# alias hax="growlnotify -a 'Activity Monitor' 'System error' -m 'WTF R U DOIN'"
#
# alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"
#
# # Lock the screen (when going AFK)
# alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
#
# # Reload the shell (i.e. invoke as a login shell)
# alias reload="exec $SHELL -l"
#
# # Faster npm for europeans
# command -v npm > /dev/null && alias npme="npm --registry http://registry.npmjs.eu"
#
