#!/usr/bin/env zsh
#(FOR EDITOR FILE-TYPING ONLY)
#
##



#====================================================================
# Homebrew
##
export HOMEBREW_GITHUB_API_TOKEN=644499f58766e8eec18f3fa8875fc8e8774a3906





#-------------------------------------------------------------------------------
#  Chef Environment setup
#-------------------------------------------------------------------------------
#export OPSCODE_USER=rnobles
#export ORGNAME=munet

#====================================================================
#  Amazon EC2 Environment
#
#   TODO:  Replace with new values
####

# export AWS_ACCESS_KEY_ID=AKIAJIVJ75GMVZJKO56Q
# export AWS_SECRET_ACCESS_KEY=ila3YFCBP9YmLhcHO/w2yTyr+7DSai2FrBdglZ0v
# export AWS_SSH_KEY_ID="aws-us-west-ca"
# export EC2_KEYPAIR="aws-us-west-ca" # name only, not the file name
# export EC2_URL=https://ec2.us-west-1.amazonaws.com
# export EC2_PRIVATE_KEY=$HOME/.ssh/pk-GFSW337M3WURNRQ6OVVCIIJAMHC5ZYVN.pem
# export EC2_CERT=$HOME/.ssh/cert-GFSW337M3WURNRQ6OVVCIIJAMHC5ZYVN.pem

#====================================================================
#  JAVA Environment
#
#   Setting Java Home is system-dependent
####
os_name=$(uname -s)

case $os_name in
	Linux )
    export JAVA_HOME='/usr/lib/jvm/java-6-openjdk/' ;;
	Darwin )
		export JAVA_HOME='/usr/libexec/java_home' ;;
esac
